const EventsDetails = [
    {
      title: "NATIONAL SPACE DAY 2024",
      hosting: "By Space Exploration Society",
      club: "SES",
      description: `Exploring New Horizons: Celebrating India's Space Legacy 
      To commemorate the success of Chandrayaan-3 mission on its first anniversary, Space Exploration Society and Department of Physics at IIT Bhilai are delighted to invite you all to celebrate the National Space Day with us. Get ready to spend the day with exciting sessions of fun and knowledge outreach throughout the day to celebrate India’s greatest achievements. Looking forward for your participation to make this event a resounding success.`,
      date: "08",
      month: "Aug",
      year: "2024",
      time: "12:00-2:00 PM IST",
      location: "IIT Bhilai",
      timeLeft: "2 days left",
      image: "/events/Space_Day.jpg",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
  ];

  module.exports = EventsDetails;