const EventsDetails = [
    {
      title: "NATIONAL SPACE DAY 2024",
      hosting: "By Space Exploration Society",
      club: "SES",
      description: `Exploring New Horizons: Celebrating India's Space Legacy 
      To commemorate the success of Chandrayaan-3 mission on its first anniversary, Space Exploration Society and Department of Physics at IIT Bhilai are delighted to invite you all to celebrate the National Space Day with us. Get ready to spend the day with exciting sessions of fun and knowledge outreach throughout the day to celebrate India’s greatest achievements. Looking forward for your participation to make this event a resounding success.`,
      date: "08",
      month: "Aug",
      year: "2024",
      time: "12:00-2:00 PM IST",
      location: "IIT Bhilai",
      timeLeft: "2 days left",
      image: "/events/Space_Day.jpg",
    },
    {
      title: "CRYPTOPULSE Summer Bootcamp",
      hosting: "By Blockchain at IIT Bhilai (BIB)",
      club: "BIB",
      description: "An immersive program to explore blockchain fundamentals, development with Solidity, and industry trends. Includes hands-on workshops and expert insights.",
      date: "08",
      month: "May/June",
      year: "2024",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
    {
      title: "Summer Of Electronics",
      hosting: "By Electromos",
      club: "Electromos",
      description: "The Electromos club decided to conduct summer online workshop for the Student of our institute . This year the first Summer Of Electronics workshops were conducted. This year 3 major workshops were conducted, this included workshops on MATLAB & Simulink, PCB designing and LTspice circuit simulation. Certificate of completion were also awarded to sincere students who attended all sessions and solved the problem statements.This initiative will continue every year from now.",
      date: "08",
      month: "May/July",
      year: "2024",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "/events/PCB_S2.png",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
    {
      title: "PHOTOSHOP REVAMP BY THE GOAT",
      hosting: "Hosted by Talla",
      club: "DesignX",
      description: "This is a description of the event",
      date: "08",
      month: "Aug",
      time: "12:00-2:00 PM IST",
      location: "Bhilai",
      timeLeft: "2 days left",
      image: "https://via.placeholder.com/150",
    },
  ];

  module.exports = EventsDetails;